import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const style = cn("bg-eerie-black text-isabeline", inter.className);

  return (
    <html lang="en">
      <body className={style}>{children}</body>
    </html>
  );
}
