import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cn from "classnames";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const style = cn("text-isabeline bg-eerie-black-400", inter.className);

  return (
    <html lang="en">
      <body className={style}>
        <Header />
        {children}
      </body>
    </html>
  );
}
